### ISSUE TITLE
MonadReader instance for StateRefT

### ISSUE THREAD

**Issue by NicolasT** [fpco/monad-unlift#7]
Is there any reason why there's no `instance MonadReader r m => MonadReader r (StateRefT ref s m)`? Would this be breaking laws?

Implementation could be
```haskell
instance MonadReader r m => MonadReader r (StateRefT ref s m) where
    ask = lift ask
    local = mapStateRefT . local
    reader = lift . reader

mapStateRefT :: (m a -> n b) -> StateRefT ref s m a -> StateRefT ref s n b
mapStateRefT f m = StateRefT $ \ref -> f $ unStateRefT m ref
```
which at least typechecks (dunno about functionality).

**Comment by snoyberg** [comment]
I don't see a problem with it, PR welcome.
