### ISSUE TITLE
Missing README

### ISSUE THREAD

**Issue by MaxGabriel** [fpco/monad-unlift#9]
The docs say

> Please see the README.md file for details

And the homepage link to the README 404s: https://github.com/fpco/monad-unlift/tree/master/unliftio-core#readme

**Comment by snoyberg** [comment]
It's a link to the wrong repo, it should point to:

https://github.com/fpco/unliftio/tree/master/unliftio-core#readme

Next upload to Hackage will fix this, but I've been holding off until there
is actual code to accompany it. I suppose I could release now though.

On Thu, Dec 14, 2017 at 1:46 AM, Maximilian Tagher <notifications@github.com

**Comment by jtdaugherty** [comment]
I just ran into this, too, so I think a release just to fix this would be helpful.

**Comment by jtdaugherty** [comment]
Also, the link that @snoyberg gave above just bounces the reader to

https://www.stackage.org/package/unliftio

so I think it would be most helpful if this package links to that instead of to

https://github.com/fpco/unliftio/tree/master/unliftio-core#readme

**Comment by snoyberg** [comment]
@jtdaugherty Which package are you trying to report a problem with? Which URL are you seeing a bad link on?

**Comment by jtdaugherty** [comment]
Here's the trail I followed:
* Went to https://hackage.haskell.org/package/unliftio-0.1.0.0
* This instructed me to view the README for information, but there is no README
* Clicked this link in the package metadata as a fallback: https://github.com/fpco/monad-unlift/tree/master/unliftio#readme
* Got a 404, trimmed it down to just https://github.com/fpco/monad-unlift
* Found this repo
* Saw the mention of https://github.com/fpco/unliftio/tree/master/unliftio-core#readme above
* Clicked that
* Saw "Typically, you'll want to use the unliftio library" in the README there
* Clicked that link, got to https://www.stackage.org/package/unliftio, which provided the documentation I was after at the very beginning

**Comment by jtdaugherty** [comment]
So actually, I noticed there is definitely a README on the first step - my mistake! I didn't scroll down.

**Comment by jtdaugherty** [comment]
But I was distracted by the broken link in the package metadata, which I still think should skip over the link you provided and point to a better one. :)

**Comment by snoyberg** [comment]
You're looking at an old version of the package. Newer versions have
working links.

On Mon, Jan 8, 2018 at 1:33 PM, Jonathan Daugherty <notifications@github.com

**Comment by jtdaugherty** [comment]
Oh, sorry! I didn't notice. I tend to be able to safely assume that Google search results take me to the latest version of that page. :(

**Comment by snoyberg** [comment]
No problem. Since the new version is uploaded, I'm going to close this out.

**Comment by jtdaugherty** [comment]
Thanks! (Also, the fact that this ticket was still open was one more reason I didn't realize I had the wrong page. :) )
